version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: am_system
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: AmSystemDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - affiliate_marketing_network

  # .NET API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: university_api
    env_file:
        - .env.docker
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - affiliate_marketing_network

# Named volumes for data persistence
volumes:
  postgres_data:

# Network for service communication
networks:
  affiliate_marketing_network:
    driver: bridge
